In [1]:
import pandas as pd
import numpy as np

## Pandas

In [2]:
# Pandas is a lib that woks with dataframes
# A Dataframe is like an excel spreedsheet

# colums and rows
# In Pandas a column is a serie

# The columns name are called Features

In [3]:
# How to create a dataframe
# Series are 1D array. are the columns
# To handle 1D arrays we use Numpy lib

In [4]:
# How to create a Dataframe
# 1. Arrays
# 2. Dictionary
# 3. CSV File

### Option 1 using Array

In [5]:
# creating an array
data = np.array([[1,4], [2,5], [3,6]])

In [6]:
# creating a dataframe
df = pd.DataFrame(data, index=['row1', 'row2', 'row3'], columns=['col1', 'col2'])

In [7]:
# showing the dataframe
df

      col1  col2
row1     1     4
row2     2     5
row3     3     6

### Option 2 - create a Dataframe from a dictionary

In [8]:
# lists used for this example
states = ['Benguela', 'Navegantes', 'Lobito', 'Cubal']
population = [800030, 750000, 800000, 300008]

In [9]:
# Storing lists with a dictionary
dict_states = {'states': states, 'population': population}

In [10]:
# creating the dataframe
df_population = pd.DataFrame(dict_states)

In [11]:
# showing the databaframe
df_population

       states  population
0    Benguela      800030
1  Navegantes      750000
2      Lobito      800000
3       Cubal      300008

### 3. Creating a DataFrame from a csv file

In [12]:
# reading file
df_exams = pd.read_csv('StudentsPerformance.csv')

In [13]:
# show the firsts five rows
# csv files are datasets
# tables in pandas are dataframes
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [14]:
# show latest 5 rows in a dataframe
df_exams.tail()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [15]:
# show first n rows in a dataframe
df_exams.head(3)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93

In [16]:
# show latest n rows in a dataframe
df_exams.tail(2)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [17]:
# getting access to the shape attribute
df_exams.shape

(1000, 8)

In [18]:
# display n rows
pd.set_option('display.max_rows', 8)
# df_exams

### Attributes, Functions, Methods in Pandas

In [19]:
# Method - a function defined inside a class body
# df.head()

### 1.Attributes

In [20]:
# getting access to the shape attribute
df_exams.shape

(1000, 8)

In [21]:
# getting access to the index attribute
df_exams.index

RangeIndex(start=0, stop=1000, step=1)

In [22]:
# getting access to the column attribute
df_exams.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='str')

In [23]:
# data types of each column
df_exams.dtypes

gender                           str
race/ethnicity                   str
parental level of education      str
lunch                            str
test preparation course          str
math score                     int64
reading score                  int64
writing score                  int64
dtype: object

### 2.Methods

In [24]:
# showing the first 5 rows
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [25]:
# showing the info of the dataframe
df_exams.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   str
 1   race/ethnicity               1000 non-null   str
 2   parental level of education  1000 non-null   str
 3   lunch                        1000 non-null   str
 4   test preparation course      1000 non-null   str
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), str(5)
memory usage: 62.6 KB

In [26]:
# describing basic statistics of the dataframe
df_exams.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

### 3.Functions

In [27]:
# obtaining the length of the dataframe [number o rows]
len(df_exams)

1000

In [28]:
# obtaining the highest index of the dataframe
max(df_exams.index)

999

In [29]:
# obtaining the lowest index of the dataframe
min(df_exams.index)

0

In [30]:
# obtaining the data type
type(df_exams)

pandas.DataFrame

In [31]:
# rounding the values of the dataframe
# round(df_exams, 2)

### Selecting one Column

In [32]:
# select a column
df_exams['gender']

0      female
1      female
2      female
3        male
        ...
996      male
997    female
998    female
999    female
Name: gender, Length: 1000, dtype: str

In [33]:
# check the data type
type(df_exams['gender'])

pandas.Series

In [34]:
df_exams['gender'].head()

0    female
1    female
2    female
3      male
4      male
Name: gender, dtype: str

In [35]:
# syntax 2 to select a column
df_exams.gender

0      female
1      female
2      female
3        male
        ...
996      male
997    female
998    female
999    female
Name: gender, Length: 1000, dtype: str

In [36]:
# select a column with . (pitfalls)
df_exams['math score']

0      72
1      69
2      90
3      47
       ..
996    62
997    59
998    68
999    77
Name: math score, Length: 1000, dtype: int64

In [37]:
# select two or more columns in a dataframe using [[]]
df_exams[['gender','math score']] 
# to pais pf brackts is a dataframe, one pair is  aserie

     gender  math score
0    female          72
1    female          69
2    female          90
3      male          47
..      ...         ...
996    male          62
997  female          59
998  female          68
999  female          77

[1000 rows x 2 columns]

In [38]:
# check the data type of the selection
type(df_exams[['gender','math score']])

pandas.DataFrame

In [39]:
df_exams[['gender', 'math score', 'writing score', 'reading score']]

     gender  math score  writing score  reading score
0    female          72             74             72
1    female          69             88             90
2    female          90             93             95
3      male          47             44             57
..      ...         ...            ...            ...
996    male          62             55             55
997  female          59             65             71
998  female          68             77             78
999  female          77             86             86

[1000 rows x 4 columns]

In [40]:
# select 2 or more columns with .
# we cannot do that using . notation

### Adding a new column to a dataframe

In [41]:
# adding a new clumn to the dataframe
df_exams['language score'] = 70

In [42]:
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,70
1,female,group C,some college,standard,completed,69,90,88,70
2,female,group B,master's degree,standard,none,90,95,93,70
3,male,group A,associate's degree,free/reduced,none,47,57,44,70
...,...,...,...,...,...,...,...,...,...
996,male,group C,high school,free/reduced,none,62,55,55,70
997,female,group C,high school,free/reduced,completed,59,71,65,70
998,female,group D,some college,standard,completed,68,78,77,70
999,female,group D,some college,free/reduced,none,77,86,86,70

In [43]:
# adding a new column using array and numpy
language_score = np.arange(0,1000)

In [44]:
df_exams['language_score'] = language_score

In [45]:
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,language_score
0,female,group B,bachelor's degree,standard,none,72,72,74,70,0
1,female,group C,some college,standard,completed,69,90,88,70,1
2,female,group B,master's degree,standard,none,90,95,93,70,2
3,male,group A,associate's degree,free/reduced,none,47,57,44,70,3
...,...,...,...,...,...,...,...,...,...,...
996,male,group C,high school,free/reduced,none,62,55,55,70,996
997,female,group C,high school,free/reduced,completed,59,71,65,70,997
998,female,group D,some college,standard,completed,68,78,77,70,998
999,female,group D,some college,free/reduced,none,77,86,86,70,999

In [46]:
# creating random integer number between 1 to 100
int_language_score = np.random.randint(1, 100, size=1000)

In [47]:
# min value inclusive and high value exclusive
min(int_language_score)
max(int_language_score)

np.int64(99)

In [48]:
df_exams['language_score'] = int_language_score
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,language_score
0,female,group B,bachelor's degree,standard,none,72,72,74,70,39
1,female,group C,some college,standard,completed,69,90,88,70,78
2,female,group B,master's degree,standard,none,90,95,93,70,71
3,male,group A,associate's degree,free/reduced,none,47,57,44,70,10
...,...,...,...,...,...,...,...,...,...,...
996,male,group C,high school,free/reduced,none,62,55,55,70,33
997,female,group C,high school,free/reduced,completed,59,71,65,70,97
998,female,group D,some college,standard,completed,68,78,77,70,55
999,female,group D,some college,free/reduced,none,77,86,86,70,58

In [49]:
# create random foat number
# np.random.uniform(1,100,size=1000)

In [50]:
# creating random numbers for our new score columns
score1 = np.random.randint(1,100,size=1000)
score2 = np.random.randint(1,100,size=1000)

In [51]:
# crate series from the random numbers
series1 = pd.Series(score1, index=np.arange(0,1000))
series2 = pd.Series(score2, index=np.arange(0,1000))

In [52]:
# using assign to add a new column
df_exams = df_exams.assign(score1=series1,score2=series2)

In [53]:
# show a dataframe
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,language_score,score1,score2
0,female,group B,bachelor's degree,standard,none,72,72,74,70,39,4,94
1,female,group C,some college,standard,completed,69,90,88,70,78,67,6
2,female,group B,master's degree,standard,none,90,95,93,70,71,17,22
3,male,group A,associate's degree,free/reduced,none,47,57,44,70,10,50,83
...,...,...,...,...,...,...,...,...,...,...,...,...
996,male,group C,high school,free/reduced,none,62,55,55,70,33,9,56
997,female,group C,high school,free/reduced,completed,59,71,65,70,97,55,62
998,female,group D,some college,standard,completed,68,78,77,70,55,46,81
999,female,group D,some college,free/reduced,none,77,86,86,70,58,47,93

### New Column with insert method

In [54]:
# adding with specific position
df_exams.insert(1, "test", series1)

In [55]:
df_exams

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,language_score,score1,score2
0,female,4,group B,bachelor's degree,standard,none,72,72,74,70,39,4,94
1,female,67,group C,some college,standard,completed,69,90,88,70,78,67,6
2,female,17,group B,master's degree,standard,none,90,95,93,70,71,17,22
3,male,50,group A,associate's degree,free/reduced,none,47,57,44,70,10,50,83
...,...,...,...,...,...,...,...,...,...,...,...,...,...
996,male,9,group C,high school,free/reduced,none,62,55,55,70,33,9,56
997,female,55,group C,high school,free/reduced,completed,59,71,65,70,97,55,62
998,female,46,group D,some college,standard,completed,68,78,77,70,55,46,81
999,female,47,group D,some college,free/reduced,none,77,86,86,70,58,47,93

### Math Operations

In [56]:
# Total sum of a column
df_exams['math score'].sum()

np.int64(66089)

In [57]:
df_exams['math score'].count()

np.int64(1000)

In [58]:
df_exams['math score'].mean()

np.float64(66.089)

In [59]:
df_exams['math score'].min()

np.int64(0)

In [60]:
df_exams['math score'].max()

np.int64(100)

In [61]:
df_exams['math score'].std()

np.float64(15.16308009600945)

In [62]:
# easier calculation with describe
df_exams.describe()

,test,math score,reading score,writing score,language score,language_score,score1,score2
count,1000.000000,1000.00000,1000.000000,1000.000000,1000.0,1000.000000,1000.000000,1000.000000
mean,49.927000,66.08900,69.169000,68.054000,70.0,50.289000,49.927000,50.299000
std,28.274673,15.16308,14.600192,15.195657,0.0,28.074858,28.274673,28.612625
min,1.000000,0.00000,17.000000,10.000000,70.0,1.000000,1.000000,1.000000
25%,26.000000,57.00000,59.000000,57.750000,70.0,26.000000,26.000000,26.000000
50%,51.000000,66.00000,70.000000,69.000000,70.0,50.000000,51.000000,50.000000
75%,74.250000,77.00000,79.000000,79.000000,70.0,74.000000,74.250000,75.000000
max,99.000000,100.00000,100.000000,100.000000,70.0,99.000000,99.000000,99.000000

### 1.2 Operations in rows

In [63]:
# calculating the sum in a row
df_exams['math score'] + df_exams['reading score'] + df_exams['writing score']

0      218
1      247
2      278
3      148
      ...
996    172
997    195
998    223
999    249
Length: 1000, dtype: int64

In [66]:
# average
df_exams['average'] = (df_exams['math score'] + df_exams['reading score'] + df_exams['writing score'])/3

In [68]:
df_exams.round(2)

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,language_score,score1,score2,average
0,female,4,group B,bachelor's degree,standard,none,72,72,74,70,39,4,94,72.67
1,female,67,group C,some college,standard,completed,69,90,88,70,78,67,6,82.33
2,female,17,group B,master's degree,standard,none,90,95,93,70,71,17,22,92.67
3,male,50,group A,associate's degree,free/reduced,none,47,57,44,70,10,50,83,49.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
996,male,9,group C,high school,free/reduced,none,62,55,55,70,33,9,56,57.33
997,female,55,group C,high school,free/reduced,completed,59,71,65,70,97,55,62,65.00
998,female,46,group D,some college,standard,completed,68,78,77,70,55,46,81,74.33
999,female,47,group D,some college,free/reduced,none,77,86,86,70,58,47,93,83.00

## 1 Value Counts

In [69]:
# countig gender elements

# len function
len(df_exams['gender'])

# .count() method
df_exams['gender'].count()

np.int64(1000)

In [70]:
# counting gender elements by category
df_exams['gender'].value_counts()

gender
female    518
male      482
Name: count, dtype: int64

In [71]:
# return relative frequency (percentage)
df_exams['gender'].value_counts(normalize=True)

gender
female    0.518
male      0.482
Name: proportion, dtype: float64

In [72]:
# counting "parental level of education" elements by category
df_exams['parental level of education'].value_counts()

parental level of education
some college          226
associate's degree    222
high school           196
some high school      179
bachelor's degree     118
master's degree        59
Name: count, dtype: int64