In [1]:
import pandas as pd
import numpy as np
import random

In [2]:
# reading file
df_exams = pd.read_csv('StudentsPerformance.csv')

In [3]:
# sort by one column
df_exams.sort_values(by='math score')

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
59,female,group C,some high school,free/reduced,none,0,17,10
980,female,group B,high school,free/reduced,none,8,24,23
17,female,group B,some high school,free/reduced,none,18,32,28
787,female,group B,some college,standard,none,19,38,32
145,female,group C,some college,free/reduced,none,22,39,33
...,...,...,...,...,...,...,...,...
623,male,group A,some college,standard,completed,100,96,86
625,male,group D,some college,standard,completed,100,97,99
962,female,group E,associate's degree,standard,none,100,100,100
458,female,group E,bachelor's degree,standard,none,100,100,100
916,male,group E,bachelor's degree,standard,completed,100,100,100

In [4]:
# sort descending by one column
df_exams.sort_values(by='math score', ascending=False)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
451,female,group E,some college,standard,none,100,92,97
458,female,group E,bachelor's degree,standard,none,100,100,100
962,female,group E,associate's degree,standard,none,100,100,100
149,male,group E,associate's degree,free/reduced,completed,100,100,93
623,male,group A,some college,standard,completed,100,96,86
...,...,...,...,...,...,...,...,...
145,female,group C,some college,free/reduced,none,22,39,33
787,female,group B,some college,standard,none,19,38,32
17,female,group B,some high school,free/reduced,none,18,32,28
980,female,group B,high school,free/reduced,none,8,24,23
59,female,group C,some high school,free/reduced,none,0,17,10

In [5]:
# sort by multiple columns
df_exams.sort_values(by=['math score', 'reading score'])

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
59,female,group C,some high school,free/reduced,none,0,17,10
980,female,group B,high school,free/reduced,none,8,24,23
17,female,group B,some high school,free/reduced,none,18,32,28
787,female,group B,some college,standard,none,19,38,32
145,female,group C,some college,free/reduced,none,22,39,33
...,...,...,...,...,...,...,...,...
625,male,group D,some college,standard,completed,100,97,99
149,male,group E,associate's degree,free/reduced,completed,100,100,93
458,female,group E,bachelor's degree,standard,none,100,100,100
916,male,group E,bachelor's degree,standard,completed,100,100,100
962,female,group E,associate's degree,standard,none,100,100,100

In [6]:
# sort descending by multiple columns
df_exams.sort_values(by=['math score', 'reading score'], ascending=False)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
149,male,group E,associate's degree,free/reduced,completed,100,100,93
458,female,group E,bachelor's degree,standard,none,100,100,100
916,male,group E,bachelor's degree,standard,completed,100,100,100
962,female,group E,associate's degree,standard,none,100,100,100
625,male,group D,some college,standard,completed,100,97,99
...,...,...,...,...,...,...,...,...
145,female,group C,some college,free/reduced,none,22,39,33
787,female,group B,some college,standard,none,19,38,32
17,female,group B,some high school,free/reduced,none,18,32,28
980,female,group B,high school,free/reduced,none,8,24,23
59,female,group C,some high school,free/reduced,none,0,17,10

In [7]:
# sort descending by multiple columns and update the dataframe
df_exams.sort_values(by=['math score', 'reading score'], ascending=False, inplace=True)

In [8]:
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
149,male,group E,associate's degree,free/reduced,completed,100,100,93
458,female,group E,bachelor's degree,standard,none,100,100,100
916,male,group E,bachelor's degree,standard,completed,100,100,100
962,female,group E,associate's degree,standard,none,100,100,100
625,male,group D,some college,standard,completed,100,97,99
...,...,...,...,...,...,...,...,...
145,female,group C,some college,free/reduced,none,22,39,33
787,female,group B,some college,standard,none,19,38,32
17,female,group B,some high school,free/reduced,none,18,32,28
980,female,group B,high school,free/reduced,none,8,24,23
59,female,group C,some high school,free/reduced,none,0,17,10

In [9]:
# sort with text using a key function
df_exams.sort_values('race/ethnicity', ascending=True, key=lambda col:col.str.lower())

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
741,female,group A,associate's degree,free/reduced,none,37,57,56
151,male,group A,bachelor's degree,standard,none,77,67,68
811,male,group A,high school,free/reduced,none,45,47,49
112,male,group A,associate's degree,standard,none,54,53,47
25,male,group A,master's degree,free/reduced,none,73,74,72
...,...,...,...,...,...,...,...,...
751,male,group E,some college,standard,none,68,72,65
915,female,group E,some college,standard,none,68,70,66
592,male,group E,bachelor's degree,standard,none,68,68,64
479,male,group E,associate's degree,standard,none,76,71,67
517,female,group E,some college,standard,completed,66,74,73

## 1 Create Index

In [11]:
# creating non repetitive values for the index
new_index = np.arange(0, 1000)
new_index

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181,
       182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194,
       195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207,
       208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220,
       221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233,
       234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246,
       247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259,
       260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272,
       273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285,
       286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298,
       299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311,
       312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324,
       325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337,
       338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350,
       351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363,
       364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376,
       377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389,
       390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402,
       403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415,
       416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428,
       429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441,
       442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454,
       455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467,
       468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480,
       481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493,
       494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506,
       507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519,
       520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532,
       533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544, 545,
       546, 547, 548, 549, 550, 551, 552, 553, 554, 555, 556, 557, 558,
       559, 560, 561, 562, 563, 564, 565, 566, 567, 568, 569, 570, 571,
       572, 573, 574, 575, 576, 577, 578, 579, 580, 581, 582, 583, 584,
       585, 586, 587, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597,
       598, 599, 600, 601, 602, 603, 604, 605, 606, 607, 608, 609, 610,
       611, 612, 613, 614, 615, 616, 617, 618, 619, 620, 621, 622, 623,
       624, 625, 626, 627, 628, 629, 630, 631, 632, 633, 634, 635, 636,
       637, 638, 639, 640, 641, 642, 643, 644, 645, 646, 647, 648, 649,
       650, 651, 652, 653, 654, 655, 656, 657, 658, 659, 660, 661, 662,
       663, 664, 665, 666, 667, 668, 669, 670, 671, 672, 673, 674, 675,
       676, 677, 678, 679, 680, 681, 682, 683, 684, 685, 686, 687, 688,
       689, 690, 691, 692, 693, 694, 695, 696, 697, 698, 699, 700, 701,
       702, 703, 704, 705, 706, 707, 708, 709, 710, 711, 712, 713, 714,
       715, 716, 717, 718, 719, 720, 721, 722, 723, 724, 725, 726, 727,
       728, 729, 730, 731, 732, 733, 734, 735, 736, 737, 738, 739, 740,
       741, 742, 743, 744, 745, 746, 747, 748, 749, 750, 751, 752, 753,
       754, 755, 756, 757, 758, 759, 760, 761, 762, 763, 764, 765, 766,
       767, 768, 769, 770, 771, 772, 773, 774, 775, 776, 777, 778, 779,
       780, 781, 782, 783, 784, 785, 786, 787, 788, 789, 790, 791, 792,
       793, 794, 795, 796, 797, 798, 799, 800, 801, 802, 803, 804, 805,
       806, 807, 808, 809, 810, 811, 812, 813, 814, 815, 816, 817, 818,
       819, 820, 821, 822, 823, 824, 825, 826, 827, 828, 829, 830, 831,
       832, 833, 834, 835, 836, 837, 838, 839, 840, 841, 842, 843, 844,
       845, 846, 847, 848, 849, 850, 851, 852, 853, 854, 855, 856, 857,
       858, 859, 860, 861, 862, 863, 864, 865, 866, 867, 868, 869, 870,
       871, 872, 873, 874, 875, 876, 877, 878, 879, 880, 881, 882, 883,
       884, 885, 886, 887, 888, 889, 890, 891, 892, 893, 894, 895, 896,
       897, 898, 899, 900, 901, 902, 903, 904, 905, 906, 907, 908, 909,
       910, 911, 912, 913, 914, 915, 916, 917, 918, 919, 920, 921, 922,
       923, 924, 925, 926, 927, 928, 929, 930, 931, 932, 933, 934, 935,
       936, 937, 938, 939, 940, 941, 942, 943, 944, 945, 946, 947, 948,
       949, 950, 951, 952, 953, 954, 955, 956, 957, 958, 959, 960, 961,
       962, 963, 964, 965, 966, 967, 968, 969, 970, 971, 972, 973, 974,
       975, 976, 977, 978, 979, 980, 981, 982, 983, 984, 985, 986, 987,
       988, 989, 990, 991, 992, 993, 994, 995, 996, 997, 998, 999])

In [12]:
# shuffling the indexes
random.shuffle(new_index)

In [13]:
new_index

array([137, 401, 220, 579, 476, 657, 130, 112, 816,  89, 538, 685, 545,
       919, 280, 868, 386, 348, 643, 298, 272, 927, 917, 565, 931, 845,
       577, 856, 337, 717, 594, 731, 182, 432,  27, 720, 877, 704, 479,
       378, 795, 291, 221, 745, 568, 753, 309, 698, 700, 604, 619, 444,
       227, 687, 293,  26, 739, 513, 160, 508, 174, 983, 711, 925, 850,
       424, 168, 145, 511, 231, 244,   1, 319, 981, 294, 860, 307, 446,
       678, 950, 641, 284, 937, 871, 305, 986, 488, 846, 225, 484, 667,
       142, 901, 172, 834, 411, 576, 119,  56, 240, 761, 162, 658, 830,
       404, 569, 654,  59, 559,  97, 535, 863, 447, 501, 459, 808, 122,
       689, 377, 730, 304, 452, 779, 277, 681, 894, 360, 932, 889, 515,
       677,   2, 540, 564, 661, 148, 504,  46,  32, 196, 149,  76,  84,
       801, 265, 106,  34, 615, 598,  28, 253, 924, 588, 325, 800, 505,
       389,  44, 317, 961, 946, 905, 497, 464, 813, 740, 767, 197, 765,
       655, 774, 534, 682, 247, 616,  98, 890, 625, 423, 198, 593, 640,
       719, 866, 487, 910, 547,  48, 405, 374, 522,  64, 874,  82, 273,
       416, 490, 473, 428, 321, 455, 463, 898, 113, 316, 554, 255, 710,
        12,  91, 921, 345, 631, 973, 818, 882, 886, 183, 229, 268,  13,
       426, 469, 806, 783,   8, 144, 826, 626,  96, 614, 542, 114, 706,
       437, 672, 339, 215, 322, 596, 964, 775, 388, 945, 222, 347, 954,
       219, 234, 214, 433, 195,  22, 880, 477, 841, 329, 676,  33, 963,
        24, 524, 562, 600, 429, 443, 308, 718, 859, 707, 811, 286, 571,
        20, 188,   7, 530, 107, 792, 492, 135, 789,  66, 368, 110, 312,
       523, 123, 758, 728, 741, 288, 567, 847, 207, 532, 960, 622, 503,
       543, 884,  14,  40, 842, 955, 445, 878, 840, 636,  95, 561, 909,
       391, 262,  17,  67, 987, 111, 205, 467, 957, 202, 855, 549, 133,
       578, 457, 812, 928, 164, 450, 434,  77, 361, 757, 915,   3, 734,
       770, 138, 173, 827,  61, 666, 258, 959,  99, 371, 104, 366, 716,
       635, 605, 489, 335,  80, 287, 440,  47, 990, 103, 146, 805, 953,
       935, 896, 996, 873, 326, 673, 776, 383, 592, 118, 585, 936, 152,
       408, 709, 328, 365, 819,  62, 124, 639,  21, 580, 170, 784, 684,
       211, 392, 462, 257, 967, 539, 302, 782, 482, 358, 629, 572, 759,
       972, 519, 727,  92, 940, 837, 895,  10,  39, 962, 259,  30, 264,
       583, 491, 574,  25, 984, 752, 885, 638, 662, 815, 512, 708,   9,
         6, 599, 627, 241,  88,  65, 908, 334, 912, 132, 342,  19, 575,
       372, 224, 858, 120, 101, 454, 267, 236, 521, 154, 353, 988, 251,
       793, 147, 903, 737, 810, 744, 217, 566, 344,  70, 318, 480, 650,
       237, 333, 117, 892, 803, 900, 324, 714, 725, 203, 697, 751, 210,
       278, 269, 760, 536, 620, 645, 233,  37, 754, 729, 608, 617, 836,
       283, 941, 128, 390, 263, 742, 646, 923, 865, 584, 825, 299,  31,
       888, 109, 431, 659, 738, 481, 239, 483, 108, 979, 486, 624, 922,
       705, 412, 907, 136, 773,  78, 187, 141, 862, 804, 851, 974, 165,
       496, 370, 929, 998, 363, 637, 533, 438, 997, 153, 939, 920,  18,
       156, 769,  86, 526, 623, 232, 829, 573, 976, 323, 849, 589,  11,
       292, 531, 185,  94, 116, 527, 602, 560, 965, 649, 835, 607, 242,
       158, 763,  50, 680, 184, 381, 794, 887, 606, 820, 502,  36, 911,
       722, 802,  90, 610, 875, 595, 876, 958, 933, 398, 975,  53, 115,
       582, 916, 980, 448, 282, 396, 999, 772, 831, 557,  81, 897, 796,
       131, 155,   4, 870, 848, 192,  16, 151, 256, 498, 785, 612,  23,
        63, 495, 379, 630, 260, 537, 768,  60, 891, 179, 951, 647, 668,
       798, 735, 394, 451, 713,  73, 587, 952, 121, 726, 356, 591, 126,
       275, 786, 797, 823, 558, 159, 696, 766, 663, 346, 306, 245, 947,
       261, 843,  38, 844, 506, 139, 355,   0, 854, 235, 407, 143, 790,
       100,  72, 279, 809, 194, 295, 343, 387, 633, 199, 385, 359, 548,
       478, 327, 422, 468, 340, 743,  35, 652, 956, 520, 475, 206, 507,
        55, 161, 413, 723, 864, 590, 799, 204, 695,  43, 216, 926, 664,
       250, 861, 102, 881,  74, 301, 872, 833, 417, 252, 439, 310, 995,
        71, 274, 852, 213, 223, 380, 942, 369, 648,   5, 724, 675, 409,
       336, 209,  83, 644, 570, 613, 546,  49, 271, 683, 290, 621, 651,
       350, 693, 525, 750, 978, 994, 332, 176, 190, 828, 493, 208,  87,
        54, 732, 701, 410,  45, 351, 314, 634, 500, 186, 971, 913, 893,
       944,  68, 400, 300, 485, 977, 494, 472, 364, 853, 541, 226, 653,
       781, 609, 150,  79, 357, 499, 341, 989, 839, 817, 736, 867, 611,
       712, 691, 553, 296, 338, 771, 285, 914, 982, 528, 992, 458, 991,
       460, 949, 906, 243, 601, 702, 140, 746, 166, 904, 674, 465, 509,
       375, 529, 436, 471, 514, 399, 943, 993, 129, 824,  57, 552, 393,
       349, 384, 266, 938, 715,  29, 660,  51,  41, 362, 628,  42, 105,
       632, 822, 762, 688, 556, 200, 787, 821, 193, 175, 563, 402, 669,
       966, 671, 430, 352, 297, 367, 414, 415, 453, 427, 461,  75, 441,
       780, 814, 313, 756, 163, 679, 127, 218, 968, 189, 157, 421, 670,
       969, 838, 248, 276, 171, 930, 883, 191, 597, 134, 642, 331,  93,
       899, 320, 456, 948, 902, 603, 181, 249, 985, 703,  69, 586,  52,
       238, 289, 382, 397, 201, 406, 167, 180,  15, 832, 544, 403, 376,
       435, 169, 330, 551, 418,  58, 555, 303, 694, 656, 354, 466, 425,
       764, 721, 270, 518,  85, 281, 420, 777, 788, 581, 315, 510, 177,
       228, 550, 212, 395, 665, 807, 692, 373, 517, 869, 230, 857, 442,
       246, 686, 755, 934, 311, 733, 747, 749, 618, 470, 449, 516, 474,
       125, 748, 690, 970, 918, 791, 419, 699, 254, 879, 778, 178])

In [14]:
# create a new column with the new index
df_exams['new_index'] = new_index

In [15]:
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,new_index
149,male,group E,associate's degree,free/reduced,completed,100,100,93,137
458,female,group E,bachelor's degree,standard,none,100,100,100,401
916,male,group E,bachelor's degree,standard,completed,100,100,100,220
962,female,group E,associate's degree,standard,none,100,100,100,579
625,male,group D,some college,standard,completed,100,97,99,476
...,...,...,...,...,...,...,...,...,...
145,female,group C,some college,free/reduced,none,22,39,33,699
787,female,group B,some college,standard,none,19,38,32,254
17,female,group B,some high school,free/reduced,none,18,32,28,879
980,female,group B,high school,free/reduced,none,8,24,23,778
59,female,group C,some high school,free/reduced,none,0,17,10,178

In [17]:
# set a new index to the dataframe
df_exams.set_index('new_index', inplace=True)

In [18]:
# sort by index
df_exams.sort_index()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
new_index,,,,,,,,
0,male,group D,some college,standard,none,60,63,59
1,male,group B,some college,standard,completed,88,85,76
2,female,group C,some college,standard,none,83,83,90
3,male,group B,high school,standard,completed,73,71,68
4,female,group C,some college,free/reduced,none,62,67,62
...,...,...,...,...,...,...,...,...
995,male,group C,bachelor's degree,standard,none,58,55,48
996,female,group C,some high school,free/reduced,completed,71,84,87
997,female,group D,associate's degree,standard,none,65,69,70
998,female,group E,bachelor's degree,standard,none,65,73,75
999,female,group C,some college,free/reduced,none,62,72,70

In [21]:
# descending sort by index
df_exams.sort_index(ascending=False, inplace=True)
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
new_index,,,,,,,,
999,female,group C,some college,free/reduced,none,62,72,70
998,female,group E,bachelor's degree,standard,none,65,73,75
997,female,group D,associate's degree,standard,none,65,69,70
996,female,group C,some high school,free/reduced,completed,71,84,87
995,male,group C,bachelor's degree,standard,none,58,55,48
...,...,...,...,...,...,...,...,...
4,female,group C,some college,free/reduced,none,62,67,62
3,male,group B,high school,standard,completed,73,71,68
2,female,group C,some college,standard,none,83,83,90
1,male,group B,some college,standard,completed,88,85,76
0,male,group D,some college,standard,none,60,63,59